apiVersion: v1
kind: Pod
metadata:
  name: hello-gpu
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - image: ski2per/hello-python
    name: hello-python
    ports:
    - containerPort: 80
      protocol: TCP
